# Aplikacja A - Service i Deployment
apiVersion: v1
kind: Service
metadata:
  name: service-a
  labels:
    app: combined-app
spec:
  selector:
    app: combined-app
  ports:
  - name: app1-port
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30000  # Wybierz odpowiedni numer portu na węźle
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  labels:
    app: combined-app
    app-name: app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
      app-name: app1
  template:
    metadata:
      labels:
        app: combined-app
        app-name: app1
    spec:
      containers:
      - name: app1-container
        image: mkopczewski/app-a-image
        ports:
        - containerPort: 5000
          protocol: TCP
        resources:
          limits:
            memory: "500Mi"
            cpu: "500m"

---
# Aplikacja B - Service i Deployment
apiVersion: v1
kind: Service
metadata:
  name: service-b
  labels:
    app: combined-app
spec:
  selector:
    app: combined-app
  ports:
  - name: app-b-port
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31000  # Wybierz odpowiedni numer portu na węźle
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-b-deployment
  labels:
    app: combined-app
    app-name: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: combined-app
      app-name: app2
  template:
    metadata:
      labels:
        app: combined-app
        app-name: app2
    spec:
      containers:
      - name: app2-container
        image: mkopczewski/app-b-image
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            memory: "1Gi"
            cpu: "1"

---
# MongoDB - PersistentVolumeClaim i StatefulSet
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "2Gi"  # Poprawiona jednostka na MiB

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest  
          ports:
            - containerPort: 27017
          resources:
            limits:
              memory: "2Gi"
              cpu: "2"
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc
