apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: bW9uZ29hZG1pbg==  # base64 "mongoadmin"
  mongo-root-password: c2VjcmV0cGFzc3dvcmQ=  # base64 "secretpassword"
