apiVersion: v1
kind: Service
metadata:
  name: service-a  # Nazwa serwisu
  labels:
    app: combined-app  # Etykieta serwisu
spec:
  selector:
    app: combined-app  # ? nwm
  ports:
  - name: app1-port
    port: 80  # Port aplikacji wystawionej na świat
    protocol: TCP
    targetPort: 5001  # Port w kontenerze
 
  type: LoadBalancer  

---

# Deployment wystawionej na świat usługi a
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-a-deployment
  labels:
    app: combined-app  
    app-name: app1  
spec:
  replicas: 2
  selector:
    matchLabels:
      app: combined-app  # Selector do podów zarządzanych przez ten deployment
      app-name: app1  # Selector dla pierwszej aplikacji
  template:
    metadata:
      labels:
        app: combined-app  # Etykieta przypisana do szablonu poda
        app-name: app1  # Etykieta przypisana do pierwszej aplikacji
    spec:
      containers:
      - name: app1-container  
        image: mkopczewski/app-a-image
        ports:
        - containerPort: 80
          protocol: TCP  
        resources:
          limits:
            memory: "100Mi"
            cpu: "100m"

