services:
  app:
    image: golangapp
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - myNetwork
    healthcheck:
          test: curl --fail http://localhost:3000/ || exit 1
          interval: 20s
          timeout: 5s
          retries: 3
          start_period: 60s
    restart: always

  reverse-proxy:
    image: reverse-proxy
    build:
      context: ./nginx
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - myNetwork
    depends_on:
      - app
    # restart: always
    environment:
      - NGINX_PORT=80  

networks:
  myNetwork:
    driver: bridge