version: '3.4'

services:
  db:
    build: ./database
    restart: always
    shm_size: 128mb
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: redis
    restart: always
    command: redis-server --requirepass admin
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

  app:
    build: ./app
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
      - redis
    command: node server.mjs

  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db-data:
  redis-data:
